apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    osInfo: ubuntu,20.04,amd64
    run.tanzu.vmware.com/resolve-tkr: ""
    tkg/plan: dev
  labels:
    tkg.tanzu.vmware.com/cluster-name: multi-tenant-platform
  name: multi-tenant-platform
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  topology:
    class: tkg-aws-default-v1.0.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: ami-region=us-west-2,os-name=ubuntu,os-arch=amd64
      replicas: 1
    variables:
    - name: cni
      value: antrea
    - name: controlPlaneCertificateRotation
      value:
        activate: true
        daysBefore: 90
    - name: auditLogging
      value:
        enabled: true
    - name: podSecurityStandard
      value:
        audit: baseline
        deactivated: false
        warn: baseline
    - name: region
      value: us-west-2
    - name: sshKeyName
      value: tkg
    - name: loadBalancerSchemeInternal
      value: false
    - name: bastion
      value:
        enabled: true
    - name: network
      value:
        subnets:
        - az: us-west-2a
          private:
            id: subnet-045395b5aa59b9986
          public:
            id: subnet-062f1f8b1b331ec61
        vpc:
          cidr: 10.0.0.0/16
          existingID: vpc-0c6c10acc9d65ab2b
    - name: identityRef
      value:
        kind: AWSClusterRoleIdentity
    - name: worker
      value:
        instanceType: m5.large
        rootVolume:
          sizeGiB: 80
    - name: controlPlane
      value:
        instanceType: t3.large
        rootVolume:
          sizeGiB: 80
    version: v1.24.9+vmware.1
    workers:
      machineDeployments:
      - class: tkg-worker
        failureDomain: us-west-2a
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: ami-region=us-west-2,os-name=ubuntu,os-arch=amd64
        name: md-0
        replicas: 1
