---
deployment:
  args:
    - --source=ingress
    - --source=contour-httpproxy
    - --domain-filter=tkg.samsanders.dev
    - --registry=txt
    - --txt-owner-id=tkg.samsanders.dev
    - --provider=aws
    - --aws-zone-type=public
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: secret-access-key
