apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: harbor-default-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: harbor-default-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: harbor-default-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: harbor-default-sa
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: harbor-cluster-issuer-annotation-overlay
  finalizers:
  - finalizers.packageinstall.packaging.carvel.dev/delete
  generation: 1
  name: harbor
  namespace: default
spec:
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: 2.5.3+vmware.1-tkg.1
      prereleases: {}
  serviceAccountName: harbor-default-sa
  values:
  - secretRef:
      name: harbor-default-values

---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-cluster-issuer-annotation-overlay
  namespace: default
stringData:
  harbor-cluster-issuer-annotation-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "Ingress","metadata":{"name":"harbor-ingress", "namespace":"tanzu-system-registry"}})
    ---
    #@overlay/match missing_ok=True
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        cert-manager.io/cluster-issuer: lets-encrypt-prod
