---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops
  namespace: kustomize-system
spec:
  sourceRef:
    kind: GitRepository
    name: gitops
  interval: 2m
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys