apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pgp-public-keys.yaml
- gotk-components.yaml
- gotk-sync.yaml

patchesStrategicMerge:
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      verify:
        mode: head
        secretRef:
          name: pgp-public-keys
  - |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      decryption:
        provider: sops
        secretRef:
          name: sops-keys